name: use kimi to create prototype from prd
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  prd-to-prototypes:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@prd')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@prd')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@prd')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@prd') || contains(github.event.issue.title, '@prd')))
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code for Issue Triage
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: ./prompts/game-app.md
          timeout_minutes: "60"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        env:

          # Provider configuration
          ANTHROPIC_BASE_URL: "https://api.moonshot.cn/anthropic/"       
